export type TrainingPhase = "base" | "build" | "peak" | "taper" | "recovery";
export type SessionCategory = "easy" | "quality" | "long" | "double" | "strength" | "mobility";
export type Philosophy =
  | "80_20"
  | "norwegian"
  | "lydiard"
  | "hansons"
  | "pfitzinger"
  | "daniels"
  | "japanese";
export type TargetDistance =
  | "1500m"
  | "5k"
  | "10k"
  | "half_marathon"
  | "marathon"
  | "ultra"
  | "season";

export interface Session {
  id: string;
  name: string;
  category: SessionCategory;
  targetDistances: TargetDistance[];
  phases: TrainingPhase[];
  description: string;
  structure: string;
  purpose: string;
  intensityZone: string;
  durationMinRange: number;
  durationMaxRange: number;
  distanceKmMin?: number;
  distanceKmMax?: number;
  requiresCTL?: number;
  forbiddenFor?: string[];
  philosophyPreferred?: Philosophy[];
  philosophyForbidden?: Philosophy[];
  notes?: string;
}

export const SESSION_LIBRARY: Session[] = [
  // ─── 1500M / MILE ───────────────────────────────────────────

  {
    id: "1500-01",
    name: "Easy Run",
    category: "easy",
    targetDistances: ["1500m"],
    phases: ["base", "build", "peak", "taper"],
    description: "Fully conversational easy run",
    structure: "Continuous, HR below LT1-15bpm",
    purpose: "Aerobic base, recovery between hard sessions",
    intensityZone: "Z1-Z2",
    durationMinRange: 30,
    durationMaxRange: 65,
    distanceKmMin: 6,
    distanceKmMax: 12,
  },
  {
    id: "1500-02",
    name: "Strides",
    category: "quality",
    targetDistances: ["1500m", "5k", "10k"],
    phases: ["base", "build", "peak"],
    description: "8×100m accelerations at end of easy run",
    structure: "8×100m building to 95-100% effort, full walk recovery 60-90 sec",
    purpose: "Neuromuscular activation, running economy",
    intensityZone: "Z5-Z6",
    durationMinRange: 10,
    durationMaxRange: 15,
    notes: "Always appended to easy run, never standalone",
  },
  {
    id: "1500-03",
    name: "Hill Sprints",
    category: "quality",
    targetDistances: ["1500m", "5k", "10k"],
    phases: ["base", "build"],
    description: "8-12×10 sec maximal uphill sprints",
    structure: "8-12×10 sec steep hill, walk down recovery",
    purpose: "Power development, VO2max stimulus with low injury risk",
    intensityZone: "Z6",
    durationMinRange: 30,
    durationMaxRange: 45,
  },
  {
    id: "1500-04",
    name: "Lactate Threshold Continuous",
    category: "quality",
    targetDistances: ["1500m", "5k", "10k", "half_marathon"],
    phases: ["build", "peak"],
    description: "Continuous threshold run 20-35 min",
    structure: "Continuous at LT2/T-pace, comfortably hard",
    purpose: "Raise lactate threshold",
    intensityZone: "Z4",
    durationMinRange: 20,
    durationMaxRange: 35,
    philosophyForbidden: ["norwegian"],
  },
  {
    id: "1500-05",
    name: "Cruise Intervals",
    category: "quality",
    targetDistances: ["1500m", "5k", "10k"],
    phases: ["build", "peak"],
    description: "4-6×1000m at T-pace",
    structure: "4-6×1000m with 60 sec jog recovery",
    purpose: "Threshold volume with structured recovery",
    intensityZone: "Z4",
    durationMinRange: 35,
    durationMaxRange: 55,
    philosophyPreferred: ["daniels"],
  },
  {
    id: "1500-06",
    name: "VO2max Short Intervals",
    category: "quality",
    targetDistances: ["1500m"],
    phases: ["build", "peak"],
    description: "6-10×400m at 1500m race pace",
    structure: "6-10×400m with 60-90 sec recovery",
    purpose: "VO2max, race-specific speed",
    intensityZone: "Z5",
    durationMinRange: 30,
    durationMaxRange: 50,
  },
  {
    id: "1500-07",
    name: "VO2max Medium Intervals",
    category: "quality",
    targetDistances: ["1500m"],
    phases: ["peak"],
    description: "5-8×600m at 1500m to mile pace",
    structure: "5-8×600m with 90 sec recovery",
    purpose: "VO2max endurance",
    intensityZone: "Z5",
    durationMinRange: 35,
    durationMaxRange: 55,
  },
  {
    id: "1500-08",
    name: "Race Pace Rehearsal",
    category: "quality",
    targetDistances: ["1500m"],
    phases: ["peak"],
    description: "3-5×300m at exact 1500m race pace",
    structure: "3-5×300m with full 3 min recovery",
    purpose: "Race pace specificity, confidence",
    intensityZone: "Z5-Z6",
    durationMinRange: 25,
    durationMaxRange: 40,
  },
  {
    id: "1500-09",
    name: "Short Fartlek",
    category: "quality",
    targetDistances: ["1500m", "5k"],
    phases: ["base", "build"],
    description: "Unstructured 20-30 min fartlek",
    structure: "20-30 min with 30 sec–2 min surges by feel",
    purpose: "Speed variation, mental training",
    intensityZone: "Z3-Z5 variable",
    durationMinRange: 20,
    durationMaxRange: 30,
  },
  {
    id: "1500-10",
    name: "Long Run",
    category: "long",
    targetDistances: ["1500m"],
    phases: ["base", "build", "peak"],
    description: "Easy long run 14-22km",
    structure: "Continuous easy Z1-Z2",
    purpose: "Aerobic base for middle distance runners",
    intensityZone: "Z1-Z2",
    durationMinRange: 70,
    durationMaxRange: 110,
    distanceKmMin: 14,
    distanceKmMax: 22,
  },

  // ─── 5K ─────────────────────────────────────────────────────

  {
    id: "5k-01",
    name: "Easy Run",
    category: "easy",
    targetDistances: ["5k"],
    phases: ["base", "build", "peak", "taper"],
    description: "Easy aerobic run",
    structure: "Continuous Z1-Z2, fully conversational",
    purpose: "Aerobic base",
    intensityZone: "Z1-Z2",
    durationMinRange: 40,
    durationMaxRange: 80,
    distanceKmMin: 8,
    distanceKmMax: 16,
  },
  {
    id: "5k-02",
    name: "Recovery Run",
    category: "easy",
    targetDistances: ["5k", "10k", "half_marathon", "marathon"],
    phases: ["base", "build", "peak", "taper"],
    description: "Very easy recovery run",
    structure: "Very easy Z1, 60-90 sec/km slower than easy pace",
    purpose: "Active recovery, blood flow",
    intensityZone: "Z1",
    durationMinRange: 25,
    durationMaxRange: 45,
    distanceKmMin: 5,
    distanceKmMax: 8,
  },
  {
    id: "5k-04",
    name: "Lactate Threshold Continuous",
    category: "quality",
    targetDistances: ["5k", "10k"],
    phases: ["build", "peak"],
    description: "20-40 min continuous threshold",
    structure: "Continuous at T-pace/LT2",
    purpose: "Raise lactate threshold",
    intensityZone: "Z4",
    durationMinRange: 20,
    durationMaxRange: 40,
  },
  {
    id: "5k-05",
    name: "Cruise Intervals",
    category: "quality",
    targetDistances: ["5k", "10k"],
    phases: ["build", "peak"],
    description: "5-6×1600m or 4×2000m at T-pace",
    structure: "5-6×1600m with 60 sec jog recovery",
    purpose: "High threshold volume",
    intensityZone: "Z4",
    durationMinRange: 45,
    durationMaxRange: 65,
    philosophyPreferred: ["daniels"],
  },
  {
    id: "5k-06",
    name: "Billat VO2max Intervals",
    category: "quality",
    targetDistances: ["5k"],
    phases: ["build", "peak"],
    description: "5×3 min at vVO2max",
    structure: "5×3 min with equal 3 min jog recovery",
    purpose: "Maximize time at VO2max",
    intensityZone: "Z5",
    durationMinRange: 35,
    durationMaxRange: 50,
  },
  {
    id: "5k-07",
    name: "30-30 Intervals",
    category: "quality",
    targetDistances: ["5k", "10k"],
    phases: ["build"],
    description: "30 sec at vVO2max / 30 sec jog × 20-30 reps",
    structure: "30 sec hard / 30 sec easy, 20-30 repetitions",
    purpose: "VO2max stimulus with lower injury risk",
    intensityZone: "Z5",
    durationMinRange: 25,
    durationMaxRange: 40,
  },
  {
    id: "5k-08",
    name: "1000m Repeats",
    category: "quality",
    targetDistances: ["5k"],
    phases: ["peak"],
    description: "5-8×1000m at 5K race pace",
    structure: "5-8×1000m with 90 sec–3 min recovery",
    purpose: "Race-specific VO2max",
    intensityZone: "Z5",
    durationMinRange: 40,
    durationMaxRange: 65,
  },
  {
    id: "5k-09",
    name: "Race Pace Intervals",
    category: "quality",
    targetDistances: ["5k"],
    phases: ["peak"],
    description: "4-6×1200m or 3-4×1600m at 5K pace",
    structure: "With 2-3 min recovery",
    purpose: "Race-specific adaptation",
    intensityZone: "Z5",
    durationMinRange: 35,
    durationMaxRange: 55,
  },
  {
    id: "5k-10",
    name: "Pyramid Session",
    category: "quality",
    targetDistances: ["5k", "10k"],
    phases: ["build", "peak"],
    description: "400-800-1200-1600-1200-800-400m at 5K pace",
    structure: "Equal recovery between reps",
    purpose: "Varied volume at race pace",
    intensityZone: "Z5",
    durationMinRange: 45,
    durationMaxRange: 65,
  },
  {
    id: "5k-11",
    name: "Kenyan Fartlek",
    category: "quality",
    targetDistances: ["5k", "10k", "half_marathon"],
    phases: ["base", "build"],
    description: "45-60 min unstructured fartlek",
    structure: "Unstructured surges 30 sec–3 min by feel",
    purpose: "Running feel, tactical training",
    intensityZone: "Z3-Z5 variable",
    durationMinRange: 45,
    durationMaxRange: 60,
    philosophyPreferred: ["80_20", "lydiard"],
  },
  {
    id: "5k-12",
    name: "Long Run",
    category: "long",
    targetDistances: ["5k"],
    phases: ["base", "build", "peak"],
    description: "Easy long run 18-28km",
    structure: "Continuous Z1-Z2",
    purpose: "Aerobic base",
    intensityZone: "Z1-Z2",
    durationMinRange: 85,
    durationMaxRange: 135,
    distanceKmMin: 18,
    distanceKmMax: 28,
  },

  // ─── 10K ────────────────────────────────────────────────────

  {
    id: "10k-01",
    name: "Easy Aerobic Steady",
    category: "easy",
    targetDistances: ["10k"],
    phases: ["base", "build", "peak", "taper"],
    description: "8-12 km easy aerobic — main weekday volume for 10K",
    structure: "Continuous Z1-Z2, fully conversational",
    purpose: "Aerobic support without HM/marathon midweek length",
    intensityZone: "Z1-Z2",
    durationMinRange: 40,
    durationMaxRange: 70,
    distanceKmMin: 8,
    distanceKmMax: 12,
  },
  {
    id: "10k-02",
    name: "Long Run Easy",
    category: "long",
    targetDistances: ["10k"],
    phases: ["base", "build", "peak", "taper"],
    description: "12-16 km easy — longest run of the week for 10K",
    structure: "Continuous Z1-Z2",
    purpose: "Weekly aerobic anchor; should exceed typical easy days",
    intensityZone: "Z1-Z2",
    durationMinRange: 65,
    durationMaxRange: 95,
    distanceKmMin: 12,
    distanceKmMax: 16,
  },
  {
    id: "10k-10",
    name: "Long Run Steady",
    category: "long",
    targetDistances: ["10k"],
    phases: ["build", "peak"],
    description: "14-18 km easy aerobic — progression block for 10K",
    structure: "Continuous Z1-Z2, steady rhythm",
    purpose: "Slightly longer long run in build/peak",
    intensityZone: "Z1-Z2",
    durationMinRange: 75,
    durationMaxRange: 105,
    distanceKmMin: 14,
    distanceKmMax: 18,
  },
  {
    id: "10k-03",
    name: "Lactate Threshold Continuous",
    category: "quality",
    targetDistances: ["10k"],
    phases: ["build", "peak"],
    description: "25-45 min continuous threshold",
    structure: "Continuous at T-pace/LT2",
    purpose: "Raise lactate threshold",
    intensityZone: "Z4",
    durationMinRange: 25,
    durationMaxRange: 45,
  },
  {
    id: "10k-04",
    name: "Threshold Intervals",
    category: "quality",
    targetDistances: ["10k"],
    phases: ["build", "peak"],
    description: "4-5×2000m or 3×3000m at T-pace",
    structure: "With 60-90 sec recovery",
    purpose: "High threshold volume",
    intensityZone: "Z4",
    durationMinRange: 45,
    durationMaxRange: 65,
  },
  {
    id: "10k-05",
    name: "Long Cruise Intervals",
    category: "quality",
    targetDistances: ["10k", "half_marathon"],
    phases: ["build", "peak"],
    description: "3×3200m or 2×5000m at T-pace",
    structure: "With 2 min recovery",
    purpose: "Extreme threshold endurance",
    intensityZone: "Z4",
    durationMinRange: 50,
    durationMaxRange: 75,
  },
  {
    id: "10k-07",
    name: "1200m Repeats",
    category: "quality",
    targetDistances: ["10k"],
    phases: ["build", "peak"],
    description: "5-6×1200m at 5K to 10K pace",
    structure: "With 2-3 min recovery",
    purpose: "VO2max at longer intervals",
    intensityZone: "Z5",
    durationMinRange: 40,
    durationMaxRange: 60,
  },
  {
    id: "10k-08",
    name: "10K Race Pace Intervals",
    category: "quality",
    targetDistances: ["10k"],
    phases: ["peak"],
    description: "3-5×2000m or 2-3×3000m at 10K pace",
    structure: "With 2-3 min recovery",
    purpose: "Race-specific adaptation",
    intensityZone: "Z4-Z5",
    durationMinRange: 40,
    durationMaxRange: 65,
  },
  {
    id: "10k-09",
    name: "Tempo Race Simulation",
    category: "quality",
    targetDistances: ["10k"],
    phases: ["peak"],
    description: "6-8 km continuous at 10K race pace",
    structure: "Continuous, race-like effort",
    purpose: "Race simulation",
    intensityZone: "Z4-Z5",
    durationMinRange: 30,
    durationMaxRange: 45,
  },
  {
    id: "10k-12",
    name: "General Aerobic Medium Long",
    category: "long",
    targetDistances: ["half_marathon", "marathon"],
    phases: ["base", "build"],
    description: "16-22 km moderate aerobic run",
    structure: "Z2, comfortable but not easy",
    purpose: "Aerobic volume without long run stress",
    intensityZone: "Z2",
    durationMinRange: 75,
    durationMaxRange: 110,
    distanceKmMin: 16,
    distanceKmMax: 22,
    philosophyForbidden: ["80_20"],
  },

  // ─── HALF MARATHON ──────────────────────────────────────────

  {
    id: "hm-04",
    name: "Medium Long Run",
    category: "long",
    targetDistances: ["half_marathon", "marathon"],
    phases: ["base", "build", "peak"],
    description: "18-24 km easy aerobic run",
    structure: "Continuous Z1-Z2",
    purpose: "Extra aerobic stimulus without full long run fatigue",
    intensityZone: "Z1-Z2",
    durationMinRange: 90,
    durationMaxRange: 120,
    distanceKmMin: 18,
    distanceKmMax: 24,
  },
  {
    id: "hm-07",
    name: "Long Threshold Intervals",
    category: "quality",
    targetDistances: ["half_marathon"],
    phases: ["build", "peak"],
    description: "3×3200m or 2×5000m at T-pace",
    structure: "With 2 min recovery",
    purpose: "High threshold volume",
    intensityZone: "Z4",
    durationMinRange: 50,
    durationMaxRange: 70,
  },
  {
    id: "hm-08",
    name: "HM Pace Intervals",
    category: "quality",
    targetDistances: ["half_marathon"],
    phases: ["build", "peak"],
    description: "4-5×3000m or 3×5000m at HM pace",
    structure: "With 90 sec–2 min recovery",
    purpose: "Race-specific adaptation",
    intensityZone: "Z4",
    durationMinRange: 50,
    durationMaxRange: 75,
  },
  {
    id: "hm-09",
    name: "HM Pace Tempo — Pfitzinger",
    category: "quality",
    targetDistances: ["half_marathon"],
    phases: ["peak"],
    description: "10-14 km continuous at HM race pace",
    structure: "Continuous, race-like effort",
    purpose: "Most demanding HM session, full race simulation",
    intensityZone: "Z4",
    durationMinRange: 50,
    durationMaxRange: 75,
    philosophyPreferred: ["pfitzinger"],
  },
  {
    id: "hm-10",
    name: "VO2max Intervals — Sparse",
    category: "quality",
    targetDistances: ["half_marathon"],
    phases: ["peak"],
    description: "5×1000m at 5K pace",
    structure: "With 2 min recovery",
    purpose: "Small VO2max stimulus, used sparingly",
    intensityZone: "Z5",
    durationMinRange: 30,
    durationMaxRange: 45,
    notes: "MAX 1x per 2 weeks, peak phase only",
  },
  {
    id: "hm-11",
    name: "Long Run Easy",
    category: "long",
    targetDistances: ["half_marathon"],
    phases: ["base", "build", "peak"],
    description: "22-29 km easy long run",
    structure: "Continuous Z1-Z2",
    purpose: "Aerobic base",
    intensityZone: "Z1-Z2",
    durationMinRange: 110,
    durationMaxRange: 150,
    distanceKmMin: 22,
    distanceKmMax: 29,
  },
  {
    id: "hm-12",
    name: "Progressive Long Run",
    category: "long",
    targetDistances: ["half_marathon", "marathon"],
    phases: ["build", "peak"],
    description: "24-29 km with final portion at HM/MP pace",
    structure: "First 60% Z1-Z2, next 25% Z2-Z3, final 15% at goal pace",
    purpose: "Simulate race fatigue, build specific endurance",
    intensityZone: "Z1 → Z4",
    durationMinRange: 120,
    durationMaxRange: 160,
    distanceKmMin: 24,
    distanceKmMax: 29,
  },

  // ─── MARATHON ────────────────────────────────────────────────

  {
    id: "m-01",
    name: "Easy Run",
    category: "easy",
    targetDistances: ["marathon"],
    phases: ["base", "build", "peak", "taper"],
    description: "Easy aerobic run, fully conversational",
    structure: "Continuous Z1-Z2",
    purpose: "Aerobic base, makes up 70-80% of all training",
    intensityZone: "Z1-Z2",
    durationMinRange: 45,
    durationMaxRange: 100,
    distanceKmMin: 10,
    distanceKmMax: 22,
  },
  {
    id: "m-02",
    name: "Recovery Jog",
    category: "easy",
    targetDistances: ["marathon"],
    phases: ["base", "build", "peak", "taper"],
    description: "Very light jog — legs only, finish fresher than you started",
    structure: "Continuous Z1, effort barely noticeable",
    purpose: "Active recovery the day after quality or a long run",
    intensityZone: "Z1",
    durationMinRange: 30,
    durationMaxRange: 55,
    distanceKmMin: 6,
    distanceKmMax: 14,
  },
  {
    id: "m-04",
    name: "Aerobic Foundation Run",
    category: "easy",
    targetDistances: ["marathon"],
    phases: ["base", "build"],
    description: "Steady Z2 aerobic work, still fully conversational",
    structure: "Continuous moderate aerobic",
    purpose: "Build aerobic enzymes without spike in fatigue",
    intensityZone: "Z2",
    durationMinRange: 45,
    durationMaxRange: 90,
    distanceKmMin: 10,
    distanceKmMax: 20,
  },
  {
    id: "m-03",
    name: "General Aerobic Run",
    category: "easy",
    targetDistances: ["marathon"],
    phases: ["base", "build"],
    description: "14-22 km moderate aerobic run",
    structure: "Z2, comfortable but purposeful",
    purpose: "Aerobic volume, Pfitzinger staple",
    intensityZone: "Z2",
    durationMinRange: 70,
    durationMaxRange: 110,
    distanceKmMin: 14,
    distanceKmMax: 22,
    philosophyForbidden: ["80_20"],
    philosophyPreferred: ["pfitzinger"],
  },
  {
    id: "m-05",
    name: "Lactate Threshold Continuous",
    category: "quality",
    targetDistances: ["marathon"],
    phases: ["build", "peak", "taper"],
    description: "20-40 min continuous at LT2/T-pace",
    structure: "Continuous threshold, comfortably hard",
    purpose: "Most efficient marathon quality session",
    intensityZone: "Z4",
    durationMinRange: 20,
    durationMaxRange: 40,
  },
  {
    id: "m-06",
    name: "Cruise Intervals",
    category: "quality",
    targetDistances: ["marathon"],
    phases: ["build", "peak"],
    description: "5-6×1600m or 4×2000m at T-pace",
    structure: "With 60 sec jog recovery",
    purpose: "Threshold volume",
    intensityZone: "Z4",
    durationMinRange: 50,
    durationMaxRange: 70,
    philosophyPreferred: ["daniels", "pfitzinger"],
  },
  {
    id: "m-07",
    name: "Marathon Pace Run — Short",
    category: "quality",
    targetDistances: ["marathon"],
    phases: ["build"],
    description: "12-18 km at exact marathon race pace",
    structure: "3 km EZ + 12-18 km MP + 3 km EZ",
    purpose: "Economy at race pace, glycogen utilization",
    intensityZone: "Z3-Z4",
    durationMinRange: 75,
    durationMaxRange: 110,
    distanceKmMin: 18,
    distanceKmMax: 24,
    philosophyPreferred: ["hansons", "pfitzinger"],
  },
  {
    id: "m-08",
    name: "Marathon Pace Run — Long",
    category: "quality",
    targetDistances: ["marathon"],
    phases: ["peak"],
    description: "20-26 km at exact marathon race pace",
    structure: "3 km EZ + 20-26 km MP + 3 km EZ",
    purpose: "Race-specific adaptation",
    intensityZone: "Z3-Z4",
    durationMinRange: 110,
    durationMaxRange: 150,
    distanceKmMin: 26,
    distanceKmMax: 32,
    philosophyPreferred: ["hansons", "pfitzinger"],
  },
  {
    id: "m-09",
    name: "Long Run Easy",
    category: "long",
    targetDistances: ["marathon"],
    phases: ["base", "build", "peak"],
    description: "27-38 km fully easy long run",
    structure: "Continuous Z1-Z2",
    purpose: "Aerobic base, glycogen storage, mental strength",
    intensityZone: "Z1-Z2",
    durationMinRange: 130,
    durationMaxRange: 195,
    distanceKmMin: 27,
    distanceKmMax: 38,
    forbiddenFor: ["hansons"],
  },
  {
    id: "m-10",
    name: "Progressive Long Run — Pfitzinger",
    category: "long",
    targetDistances: ["marathon"],
    phases: ["build", "peak"],
    description: "29-35 km, final third at marathon pace",
    structure: "First 18 km Z1-Z2, final 11-16 km at MP",
    purpose: "Simulate end of marathon on tired legs",
    intensityZone: "Z1-Z2 → Z3-Z4",
    durationMinRange: 150,
    durationMaxRange: 195,
    distanceKmMin: 29,
    distanceKmMax: 35,
    philosophyPreferred: ["pfitzinger", "80_20"],
  },
  {
    id: "m-11",
    name: "Back-to-Back Day 1 — Hansons",
    category: "long",
    targetDistances: ["marathon"],
    phases: ["build", "peak"],
    description: "27-32 km easy Saturday",
    structure: "Continuous Z1-Z2",
    purpose: "Day 1 of back-to-back weekend",
    intensityZone: "Z1-Z2",
    durationMinRange: 130,
    durationMaxRange: 170,
    distanceKmMin: 27,
    distanceKmMax: 32,
    philosophyPreferred: ["hansons"],
  },
  {
    id: "m-12",
    name: "Back-to-Back Day 2 — Hansons",
    category: "long",
    targetDistances: ["marathon"],
    phases: ["build", "peak"],
    description: "19-25 km Sunday, second half at MP",
    structure: "First half Z1, second half at marathon pace",
    purpose: "Marathon-specific on pre-fatigued legs",
    intensityZone: "Z1-Z2 → Z3-Z4",
    durationMinRange: 95,
    durationMaxRange: 135,
    distanceKmMin: 19,
    distanceKmMax: 25,
    philosophyPreferred: ["hansons"],
  },
  {
    id: "m-13",
    name: "Kipchoge Long Run — Elite",
    category: "long",
    targetDistances: ["marathon"],
    phases: ["peak"],
    description: "35-38 km with final 15 km at MP",
    structure: "First 20 km Z1-Z2, final 15 km at marathon pace",
    purpose: "Extreme race-specific volume",
    intensityZone: "Z1-Z2 → Z3-Z4",
    durationMinRange: 185,
    durationMaxRange: 220,
    distanceKmMin: 35,
    distanceKmMax: 38,
    requiresCTL: 85,
    notes: "Elite/sub-elite only. Min 2 years marathon training.",
  },
  {
    id: "m-14",
    name: "VO2max Intervals — Sparse",
    category: "quality",
    targetDistances: ["marathon"],
    phases: ["peak"],
    description: "5×1000m or 6×800m at 5K pace",
    structure: "With 2-3 min recovery",
    purpose: "Small VO2max stimulus",
    intensityZone: "Z5",
    durationMinRange: 35,
    durationMaxRange: 50,
    notes: "MAX 1x per 2 weeks, peak phase only. Never for Lydiard or Hansons or CTL < 60.",
    forbiddenFor: ["lydiard", "hansons"],
  },
  {
    id: "m-15",
    name: "Medium Long Run",
    category: "long",
    targetDistances: ["marathon"],
    phases: ["base", "build", "peak", "taper"],
    description: "18-25 km easy aerobic — bridges weekday volume and the weekend long run",
    structure: "Continuous Z1-Z2, conversational throughout",
    purpose: "Aerobic endurance without full long-run fatigue",
    intensityZone: "Z1-Z2",
    durationMinRange: 85,
    durationMaxRange: 130,
    distanceKmMin: 18,
    distanceKmMax: 25,
  },
  {
    id: "m-17",
    name: "Aerobic Fartlek",
    category: "quality",
    targetDistances: ["marathon"],
    phases: ["base", "build"],
    description: "45-60 min rolling surges within aerobic effort — no race-pace reps",
    structure: "2-4 min steady Z3, 1-2 min float Z2, repeat by feel",
    purpose: "Variety and rhythm without VO2 stress in early phases",
    intensityZone: "Z2-Z3",
    durationMinRange: 45,
    durationMaxRange: 65,
  },
  {
    id: "m-18",
    name: "Leg Speed Strides",
    category: "quality",
    targetDistances: ["marathon"],
    phases: ["base", "build", "peak", "taper"],
    description: "Easy run with 6-10 short accelerations — neuromuscular, not intervals",
    structure: "Mostly Z1-Z2, then 6-10×80-120m building to strong but relaxed speed, full recovery",
    purpose: "Leg turnover and economy without accumulating hard-interval fatigue",
    intensityZone: "Z3-Z4",
    durationMinRange: 45,
    durationMaxRange: 70,
    distanceKmMin: 8,
    distanceKmMax: 14,
  },
  {
    id: "m-16",
    name: "Double Run — Evening",
    category: "double",
    targetDistances: ["marathon", "ultra"],
    phases: ["build", "peak"],
    description: "6-10 km easy second run",
    structure: "Very easy Z1, always second run of the day",
    purpose: "Extra aerobic volume without CNS stress",
    intensityZone: "Z1",
    durationMinRange: 30,
    durationMaxRange: 50,
    distanceKmMin: 6,
    distanceKmMax: 10,
    requiresCTL: 65,
    notes: "Never combine with quality session on same day. Only Tuesday/Thursday.",
  },

  // ─── ULTRA ───────────────────────────────────────────────────

  {
    id: "u-01",
    name: "Easy Trail Run",
    category: "easy",
    targetDistances: ["ultra"],
    phases: ["base", "build", "peak", "taper"],
    description: "10-25 km easy trail run",
    structure: "Time-based Z1-Z2, pace irrelevant on trails",
    purpose: "Aerobic base on relevant surface",
    intensityZone: "Z1-Z2",
    durationMinRange: 50,
    durationMaxRange: 150,
    distanceKmMin: 10,
    distanceKmMax: 25,
  },
  {
    id: "u-03",
    name: "Long Run Aerobic",
    category: "long",
    targetDistances: ["ultra"],
    phases: ["base", "build", "peak"],
    description: "30-50 km or 3-6 hours easy",
    structure: "Time on feet Z1-Z2, fueling practiced",
    purpose: "Time on feet, glycogen adaptation, mental training",
    intensityZone: "Z1-Z2",
    durationMinRange: 180,
    durationMaxRange: 360,
    distanceKmMin: 30,
    distanceKmMax: 50,
  },
  {
    id: "u-04",
    name: "Back-to-Back Day 1",
    category: "long",
    targetDistances: ["ultra"],
    phases: ["build", "peak"],
    description: "30-45 km or 3-5 hours easy",
    structure: "Z1-Z2, fueling practiced",
    purpose: "Accumulate fatigue for day 2",
    intensityZone: "Z1-Z2",
    durationMinRange: 180,
    durationMaxRange: 300,
  },
  {
    id: "u-05",
    name: "Back-to-Back Day 2",
    category: "long",
    targetDistances: ["ultra"],
    phases: ["build", "peak"],
    description: "25-35 km or 2.5-4 hours on pre-fatigued legs",
    structure: "Z1-Z2 on tired legs",
    purpose: "Race-specific fatigue adaptation",
    intensityZone: "Z1-Z2",
    durationMinRange: 150,
    durationMaxRange: 240,
  },
  {
    id: "u-06",
    name: "Long Hill Repeats",
    category: "quality",
    targetDistances: ["ultra"],
    phases: ["base", "build"],
    description: "6-10×3-5 min uphill efforts",
    structure: "Z3-Z4 uphill, easy jog/walk down",
    purpose: "Mountain-specific strength, VO2max stimulus",
    intensityZone: "Z3-Z4",
    durationMinRange: 60,
    durationMaxRange: 90,
  },
  {
    id: "u-07",
    name: "Trail Fartlek",
    category: "quality",
    targetDistances: ["ultra"],
    phases: ["build"],
    description: "90-150 min terrain-based fartlek",
    structure: "Hard uphill, easy downhill and flat",
    purpose: "Terrain-specific strength and endurance",
    intensityZone: "Z1-Z4 variable",
    durationMinRange: 90,
    durationMaxRange: 150,
  },
  {
    id: "u-08",
    name: "Power Hiking",
    category: "easy",
    targetDistances: ["ultra"],
    phases: ["base", "build", "peak"],
    description: "2-4 hours power hiking on steep terrain",
    structure: "Z1-Z2, steep gradient",
    purpose: "Race-specific for high-elevation ultras",
    intensityZone: "Z1-Z2",
    durationMinRange: 120,
    durationMaxRange: 240,
    notes: "Only if race has significant elevation gain",
  },

  // ─── COMPETITION SEASON ──────────────────────────────────────

  {
    id: "s-01",
    name: "Sharpening Intervals",
    category: "quality",
    targetDistances: ["season", "1500m", "5k", "10k", "half_marathon", "marathon"],
    phases: ["peak", "taper"],
    description: "6×200m or 8×300m at mile to 1500m pace",
    structure: "Full 3-4 min recovery between reps",
    purpose: "Neuromuscular activation pre-race",
    intensityZone: "Z5-Z6",
    durationMinRange: 25,
    durationMaxRange: 40,
    notes: "5-7 days before A/B race",
  },
  {
    id: "s-02",
    name: "Pre-Race Tune-Up",
    category: "quality",
    targetDistances: ["season"],
    phases: ["peak"],
    description: "6×1000m at race pace",
    structure: "With 90 sec recovery",
    purpose: "Confirm form and pace feel",
    intensityZone: "Z4-Z5",
    durationMinRange: 40,
    durationMaxRange: 55,
    notes: "10-12 days before A race",
  },
  {
    id: "s-08",
    name: "Maintenance Threshold",
    category: "quality",
    targetDistances: ["season"],
    phases: ["build"],
    description: "20-25 min continuous threshold",
    structure: "Continuous at T-pace",
    purpose: "Maintain threshold during season without over-stressing",
    intensityZone: "Z4",
    durationMinRange: 20,
    durationMaxRange: 30,
  },

  // ─── STRENGTH ────────────────────────────────────────────────

  {
    id: "str-01",
    name: "Runner Strength Foundation",
    category: "strength",
    targetDistances: ["1500m", "5k", "10k", "half_marathon", "marathon", "ultra"],
    phases: ["base", "build"],
    description: "30-40 min runner-specific strength",
    structure:
      "Single-leg deadlift 3×8, Bulgarian split squat 3×8, hip thrust 3×12, Copenhagen plank 3×20s, soleus raise 3×15",
    purpose: "Injury prevention, running economy",
    intensityZone: "N/A",
    durationMinRange: 30,
    durationMaxRange: 40,
  },
  {
    id: "str-02",
    name: "Runner Strength Maintenance",
    category: "strength",
    targetDistances: ["1500m", "5k", "10k", "half_marathon", "marathon", "ultra"],
    phases: ["base", "build", "peak"],
    description: "20-30 min maintenance strength",
    structure:
      "Lateral band walks, single-leg calf raise, glute bridge, dead bug, hip flexor stretch",
    purpose: "Maintain strength during peak training",
    intensityZone: "N/A",
    durationMinRange: 20,
    durationMaxRange: 30,
  },

  // ─── MOBILITY ────────────────────────────────────────────────

  {
    id: "mob-01",
    name: "Post-Run Mobility",
    category: "mobility",
    targetDistances: ["1500m", "5k", "10k", "half_marathon", "marathon", "ultra"],
    phases: ["base", "build", "peak", "taper"],
    description: "10-15 min post-run stretching",
    structure:
      "Hip flexors, hamstrings, pigeon pose, quad stretch, calf stretch — 45-60 sec each",
    purpose: "Recovery, injury prevention",
    intensityZone: "N/A",
    durationMinRange: 10,
    durationMaxRange: 15,
  },
  {
    id: "mob-02",
    name: "Mobility Session",
    category: "mobility",
    targetDistances: ["1500m", "5k", "10k", "half_marathon", "marathon", "ultra"],
    phases: ["base", "build", "peak"],
    description: "30-45 min yoga-inspired mobility",
    structure: "Runner-specific focus: hips, hamstrings, calves",
    purpose: "Flexibility, recovery, injury prevention",
    intensityZone: "N/A",
    durationMinRange: 30,
    durationMaxRange: 45,
    notes: "Best placed on rest days",
  },
];

export function getSessionsForDistanceAndPhase(
  distance: TargetDistance,
  phase: TrainingPhase,
  philosophy?: Philosophy,
): Session[] {
  return SESSION_LIBRARY.filter((s) => {
    const distanceMatch = s.targetDistances.includes(distance);
    const phaseMatch = s.phases.includes(phase);
    const notForbidden = philosophy
      ? !s.philosophyForbidden?.includes(philosophy)
      : true;
    return distanceMatch && phaseMatch && notForbidden;
  });
}

export function getSessionById(id: string): Session | undefined {
  return SESSION_LIBRARY.find((s) => s.id === id);
}

export function getSessionsByCategory(
  category: SessionCategory,
  distance?: TargetDistance,
): Session[] {
  return SESSION_LIBRARY.filter((s) => {
    const catMatch = s.category === category;
    const distMatch = distance ? s.targetDistances.includes(distance) : true;
    return catMatch && distMatch;
  });
}

export function getPreferredSessions(
  distance: TargetDistance,
  phase: TrainingPhase,
  philosophy: Philosophy,
): Session[] {
  return SESSION_LIBRARY.filter((s) => {
    const distanceMatch = s.targetDistances.includes(distance);
    const phaseMatch = s.phases.includes(phase);
    const notForbidden = !s.philosophyForbidden?.includes(philosophy);
    const preferred = s.philosophyPreferred?.includes(philosophy) ?? false;
    return distanceMatch && phaseMatch && notForbidden && preferred;
  });
}
